from typing import TypedDict, List, Any, Optional

class AgentState(TypedDict):
    query: str
    action: str
    result: Any
    thought: str
    history: List[str]
    execution_history: List[dict]
    iteration_count: int
    max_iterations: int
    df_info: dict
    success: bool
    final_error: Optional[str]
    available_datasets: dict
    selected_dataset: str
    active_dataframe: str
    dataset_context: dict
    data_strategy: str
    sql_feasible: bool
    table_metadata: dict
    strategy_history: List[str]
    sql_results: Any
    strategy_switched: bool
    needs_fallback: bool
    strategy_reason: str
    sql_error: Optional[str]
    conversation_history: List[dict]
    user_context: dict
    memory_summary: str
    generated_plot: Optional[dict]
    learned_patterns: List[str]
    session_metadata: dict
    llm_response: Optional[str]
    response_metadata: Optional[dict]
    skip_llm_response: bool